services:
  - type: web
    name: flask-ocr-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:10000 server:app"
    envVars:
      - key: PORT
        value: 5000
